apiVersion: v1
kind: Service
metadata:
  name: {{ include "massdriver-debugging-webinar.fullname" . }}-failrdy
  labels:
    app: failedreadiness
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: failedreadiness