apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "massdriver-debugging-webinar.fullname" . }}-oomk
  labels:
    app: oomkilled
data:
  icanhazmemory.py: |
    import time
    var=[]
    for x in range(999999):
      var.append(str(x))
      if x % 10000 == 0:
        time.sleep(0.1)
        print(str(x))
    print("Completed!")
    
    while True:
      time.sleep(10)