apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "massdriver-debugging-webinar.fullname" . }}-oomk
  labels:
    app: oomkilled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oomkilled
  template:
    metadata:
      labels:
        app: oomkilled
    spec:
      containers:
        - name: main
          image: "python:3.11-slim"
          command: ["python"]
          args: ["icanhazmemory.py"]
          resources:
            requests:
              cpu: 0.1
              memory: "10Mi"
            limits:
              cpu: 0.5
              memory: "10Mi"
              # memory: "100Mi"
          volumeMounts:
          - mountPath: /icanhazmemory.py
            name: script
            subPath: icanhazmemory.py
      volumes:
      - name: script
        configMap: 
          name: {{ include "massdriver-debugging-webinar.fullname" . }}-oomk