apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "massdriver-debugging-webinar.fullname" . }}-clbo
  labels:
    app: crashloopbackoff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloopbackoff
  template:
    metadata:
      labels:
        app: crashloopbackoff
    spec:
      containers:
      - name: main
        image: "postgres:15.4"
        # env:
        #   - name: POSTGRES_PASSWORD
        #     value: password1234
        resources:
          requests:
            cpu: 0.1
            memory: "100Mi"